// Code generated by sysgo (gen/temporal). DO NOT EDIT.

package orders

import "context"

type Order struct {
	Id string
}
type Activities interface {
	ChargeCard(ctx context.Context, order Order) error
	SendReceipt(ctx context.Context, order Order) error
}
type ActivityOptions struct {
	TaskQueue       string
	MaxAttempts     string
	InitialInterval string
	StartToClose    string
	ScheduleToClose string
	Heartbeat       string
	Idempotent      bool
}

var Options = map[string]ActivityOptions{
	"ChargeCard":  {TaskQueue: "orders"},
	"SendReceipt": {TaskQueue: "orders"},
}
