// Code generated by sysgo (gen/temporal). DO NOT EDIT.

package orders

import (
	workflow "go.temporal.io/sdk/workflow"
	"time"
)

func ProcessOrderWorkflow(ctx workflow.Context, order Order) error {
	ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{StartToCloseTimeout: time.Minute})
	if err := workflow.ExecuteActivity(ctx, "ChargeCard", order).Get(ctx, nil); err != nil {
		return err
	}
	if err := workflow.ExecuteActivity(ctx, "SendReceipt", order).Get(ctx, nil); err != nil {
		return err
	}
	return nil
}
