#!/usr/bin/env bash
# Code generated by sysgo (gen/temporal). DO NOT EDIT.
#
# Determinism enforcement (B): run Temporal's workflowcheck analyzer as a
# vet-style check over the generated workflows, guarding against
# non-deterministic constructs. See specs/TEMPORAL.md §6.
#
# Wire this into CI as a required step, e.g. `bash workflowcheck.sh`.
set -euo pipefail

# Install the analyzer into an isolated GOBIN so it does not perturb the
# project's own tool set.
bin="$(mktemp -d)"
trap 'rm -rf "$bin"' EXIT
GOBIN="$bin" go install go.temporal.io/sdk/contrib/tools/workflowcheck@latest

# Run it as a vet tool over every package (workflowcheck only reports on
# functions registered as Temporal workflows).
go vet "-vettool=$bin/workflowcheck" ./...
