// Code generated by sysgo (gen/temporal). DO NOT EDIT.

package orders

import (
	client "go.temporal.io/sdk/client"
	worker "go.temporal.io/sdk/worker"
)

// RunWorker registers the workflows and activities on their task queues and
// blocks until interrupted. The activities implementation is the hand-written
// Activities port.
func RunWorker(c client.Client, acts Activities) error {
	var workers []worker.Worker
	w0 := worker.New(c, "orders", worker.Options{})
	w0.RegisterWorkflow(ProcessOrderWorkflow)
	w0.RegisterActivity(acts)
	workers = append(workers, w0)
	for _, w := range workers {
		if err := w.Start(); err != nil {
			return err
		}
	}
	<-worker.InterruptCh()
	for _, w := range workers {
		w.Stop()
	}
	return nil
}
