// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/sysgo/examples/combined/internal/order/domain"
)

// PlaceOrderInput is the input DTO for the PlaceOrder use case.
type PlaceOrderInput struct {
	Order domain.Order `json:"order"`
}

// PlaceOrderOutput is the output DTO for the PlaceOrder use case.
type PlaceOrderOutput struct {
}

// PlaceOrderUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type PlaceOrderUseCase interface {
	PlaceOrder(input PlaceOrderInput) (PlaceOrderOutput, error)
}
