package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

const sampleConfig = `# yaml-language-server: $schema=https://raw.githubusercontent.com/gaarutyunov/sysgo/main/schema/sysgo.schema.json
module: github.com/acme/orders

source:
  # api:
  #   base-url: http://localhost:9000
  #   project: 00000000-0000-0000-0000-000000000000
  #   commit:  00000000-0000-0000-0000-000000000000
  file: ./model.export.json

overlay:
  path: ./overlay.yaml

generate:
  domain: true
  usecases: true
  ports: true
  adapters: scaffold
  events: true
  tests: false
  importlint: true
  # cmd selects the composition root: a microservice main per context
  # (per-context), a single cobra + wire app wiring every context (mono), or
  # nothing so you wire the app yourself (off).
  cmd: per-context

ports:
  driven-dir: app/port/out
  driving-dir: app/port/in
  repository-in-domain: false

layout:
  domain: { dir: "internal/{context}/domain", package: domain }
  app: { dir: "internal/{context}/app/usecase", package: usecase }
  ports: { dir: "internal/{context}/app/port", package: port }
  adapters: { dir: "internal/{context}/adapter", package: adapter }
  cmd: { dir: "cmd/{context}d", package: main }

type-mapping: {}
import-mapping: {}
additional-imports: []

output-options:
  skip-fmt: false
  skip-prune: false
  generated-marker: "// Code generated by sysgo; DO NOT EDIT."
`

const sampleOverlay = `overlay: 1.0.0
info:
  title: Go overlay
  version: 1.0.0
actions: []
  # - target: $[?(@.declaredName=='price')]
  #   update: { x-go-type: "money.Money", x-go-type-import: "github.com/acme/money" }
  # - target: $[?(@.declaredName=='Order' && @['@type']=='PartDefinition')]
  #   update: { x-ddd-stereotype: "aggregate" }
`

func newInitCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a sysgo.yaml and an empty overlay.yaml",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := writeFile("sysgo.yaml", sampleConfig, force); err != nil {
				return err
			}
			if err := writeFile("overlay.yaml", sampleOverlay, force); err != nil {
				return err
			}
			fmt.Fprintln(cmd.OutOrStdout(), "sysgo: wrote sysgo.yaml and overlay.yaml")
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing files")
	return cmd
}

func writeFile(path, content string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", path)
		}
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
