package app_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/gaarutyunov/sysgo/internal/adapter/gotmpl"
	"github.com/gaarutyunov/sysgo/internal/adapter/osfs"
	"github.com/gaarutyunov/sysgo/internal/adapter/sysmlfile"
	"github.com/gaarutyunov/sysgo/internal/app"
	"github.com/gaarutyunov/sysgo/internal/config"
	"github.com/gaarutyunov/sysgo/internal/core/mapping"
)

func newPipeline(t *testing.T, cfg *config.Config, modelPath string) *app.Pipeline {
	t.Helper()
	renderer, err := gotmpl.New(cfg)
	if err != nil {
		t.Fatalf("renderer: %v", err)
	}
	return &app.Pipeline{
		Loader:   sysmlfile.New(modelPath),
		Builder:  mapping.New(cfg),
		Renderer: renderer,
		Writer:   osfs.New(false, false, cfg.OutputOptions.GeneratedMarker),
	}
}

func orderCfg() *config.Config {
	c := config.Default()
	c.Module = "github.com/acme/orders"
	c.Source.File = "x"
	return c
}

// TestGenerateOrderGolden runs the full pipeline against the example model and
// asserts the expected file set is produced.
func TestGenerateOrderGolden(t *testing.T) {
	out := t.TempDir()
	pl := newPipeline(t, orderCfg(), "../../examples/order/model.json")
	res, err := pl.Generate(context.Background(), out)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	want := []string{
		".go-arch-lint.yml",
		"cmd/order/main.go",
		"internal/order/adapter/in/http/place_order_use_case.go",
		"internal/order/adapter/out/gateway/payment_port.go",
		"internal/order/adapter/out/repository/order_repository.go",
		"internal/order/app/port/in/place_order_use_case.go",
		"internal/order/app/port/out/order_repository.go",
		"internal/order/app/port/out/payment_port.go",
		"internal/order/app/usecase/place_order.go",
		"internal/order/domain/charge_request.go",
		"internal/order/domain/line_item.go",
		"internal/order/domain/money.go",
		"internal/order/domain/order.go",
		"internal/order/domain/order_factory.go",
		"internal/order/domain/receipt.go",
	}
	got := append([]string(nil), res.Written...)
	sort.Strings(got)
	sort.Strings(want)
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("file set mismatch:\n got: %v\nwant: %v", got, want)
	}

	// Aggregate marker present in generated file.
	order, _ := os.ReadFile(filepath.Join(out, "internal/order/domain/order.go"))
	if !strings.Contains(string(order), "Code generated by sysgo; DO NOT EDIT.") {
		t.Fatal("generated marker missing from order.go")
	}
	if !strings.Contains(string(order), "aggregate root") {
		t.Fatal("Order not rendered as aggregate")
	}
}

// TestScaffoldOnce verifies scaffold files are not overwritten on regeneration.
func TestScaffoldOnce(t *testing.T) {
	out := t.TempDir()
	pl := newPipeline(t, orderCfg(), "../../examples/order/model.json")
	if _, err := pl.Generate(context.Background(), out); err != nil {
		t.Fatal(err)
	}
	main := filepath.Join(out, "cmd/order/main.go")
	if err := os.WriteFile(main, []byte("package main\n\nfunc main() { /* mine */ }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	res, err := pl.Generate(context.Background(), out)
	if err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(main)
	if !strings.Contains(string(data), "/* mine */") {
		t.Fatal("scaffold file was overwritten")
	}
	found := false
	for _, s := range res.Skipped {
		if s == "cmd/order/main.go" {
			found = true
		}
	}
	if !found {
		t.Fatalf("main.go not reported as skipped: %v", res.Skipped)
	}
}

// TestGeneratedCompiles writes a go.mod and runs `go build ./...` over the
// generated project, proving the scaffold is valid Go (SPEC §17).
func TestGeneratedCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compile test in -short mode")
	}
	out := t.TempDir()
	pl := newPipeline(t, orderCfg(), "../../examples/order/model.json")
	if _, err := pl.Generate(context.Background(), out); err != nil {
		t.Fatal(err)
	}
	gomod := "module github.com/acme/orders\n\ngo 1.25.11\n"
	if err := os.WriteFile(filepath.Join(out, "go.mod"), []byte(gomod), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = out
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated project failed to build: %v\n%s", err, b)
	}
}
