// Package config parses and validates the sysgo.yaml configuration file, the
// UX of which is modeled on oapi-codegen (generate flags, type/import mapping,
// user templates, overlay reference).
package config

// Config is the root of sysgo.yaml.
type Config struct {
	Module   string            `yaml:"module"`
	Source   Source            `yaml:"source"`
	Overlay  Overlay           `yaml:"overlay"`
	Generate Generate          `yaml:"generate"`
	Ports    Ports             `yaml:"ports"`
	Layout   map[string]Region `yaml:"layout"`

	TypeMapping       map[string]TypeMap `yaml:"type-mapping"`
	ImportMapping     map[string]string  `yaml:"import-mapping"`
	AdditionalImports []ImportSpec       `yaml:"additional-imports"`
	OutputOptions     OutputOptions      `yaml:"output-options"`
}

// Source selects the model ingestion mode. API and File are mutually exclusive.
type Source struct {
	API  *APISource `yaml:"api,omitempty"`
	File string     `yaml:"file,omitempty"`
}

// APISource points sysgo at a SysML v2 API Services endpoint.
type APISource struct {
	BaseURL string `yaml:"base-url"`
	Project string `yaml:"project"`
	Commit  string `yaml:"commit,omitempty"`
}

// Overlay references an OpenAPI-Overlay-style document applied before IR build.
type Overlay struct {
	Path string `yaml:"path,omitempty"`
}

// Generate toggles which artifacts are emitted.
type Generate struct {
	Domain     bool   `yaml:"domain"`
	UseCases   bool   `yaml:"usecases"`
	Ports      bool   `yaml:"ports"`
	Adapters   string `yaml:"adapters"` // off | scaffold | full
	Events     bool   `yaml:"events"`
	Tests      bool   `yaml:"tests"`
	ImportLint bool   `yaml:"importlint"`
}

// Ports controls port directory placement and repository-interface location.
type Ports struct {
	DrivenDir          string `yaml:"driven-dir"`
	DrivingDir         string `yaml:"driving-dir"`
	RepositoryInDomain bool   `yaml:"repository-in-domain"`
}

// Region maps an architectural region to a directory and package name.
// {context} is interpolated with the bounded-context name.
type Region struct {
	Dir     string `yaml:"dir"`
	Package string `yaml:"package"`
}

// TypeMap maps a SysML qualified type name to a Go type (and optional import).
type TypeMap struct {
	Type   string `yaml:"type"`
	Import string `yaml:"import,omitempty"`
}

// ImportSpec is an additional import injected into generated packages.
type ImportSpec struct {
	Package string `yaml:"package"`
	Alias   string `yaml:"alias,omitempty"`
}

// OutputOptions mirrors oapi-codegen output-options.
type OutputOptions struct {
	UserTemplates   map[string]string `yaml:"user-templates,omitempty"`
	SkipFmt         bool              `yaml:"skip-fmt"`
	SkipPrune       bool              `yaml:"skip-prune"`
	GeneratedMarker string            `yaml:"generated-marker"`
}

const (
	// AdaptersOff disables adapter emission.
	AdaptersOff = "off"
	// AdaptersScaffold emits adapter stubs (scaffold-once).
	AdaptersScaffold = "scaffold"
	// AdaptersFull emits adapters fully.
	AdaptersFull = "full"

	// DefaultMarker is the canonical Go generated-code marker.
	DefaultMarker = "// Code generated by sysgo; DO NOT EDIT."
)
