// Code generated by sysgo; DO NOT EDIT.

package domain

// ChargeRequest is a value object: immutable and compared by value.
type ChargeRequest struct {
	Amount float64 `json:"amount"`
}

// Equal reports whether two ChargeRequest values are equal.
func (c ChargeRequest) Equal(other ChargeRequest) bool {
	return c == other
}
