// Code generated by sysgo; DO NOT EDIT.

package domain

// LineItem is a value object: immutable and compared by value.
type LineItem struct {
	Sku string `json:"sku"`
	Qty int64  `json:"qty"`
}

// Equal reports whether two LineItem values are equal.
func (l LineItem) Equal(other LineItem) bool {
	return l == other
}
