// Code generated by sysgo; DO NOT EDIT.

package domain

// Money is a value object: immutable and compared by value.
type Money struct {
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
}

// Equal reports whether two Money values are equal.
func (m Money) Equal(other Money) bool {
	return m == other
}
