// Code generated by sysgo; DO NOT EDIT.

package domain

// NewOrder is a factory that constructs a valid Order aggregate.
// Add invariant checks here; return an error when they are violated.
func NewOrder() (*Order, error) {
	return &Order{}, nil
}
