// Code generated by sysgo; DO NOT EDIT.

package domain

// Order is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type Order struct {
	ID    string     `json:"id"`
	Total Money      `json:"total"`
	Lines []LineItem `json:"lines"`
}
