// Code generated by sysgo; DO NOT EDIT.

package domain

// Receipt is a value object: immutable and compared by value.
type Receipt struct {
	ID string `json:"id"`
}

// Equal reports whether two Receipt values are equal.
func (r Receipt) Equal(other Receipt) bool {
	return r == other
}
