// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
)

// OrderContextOrder defines model for OrderContext.Order.
type OrderContextOrder struct {
	Id    string `json:"id"`
	Lines struct {
		Qty int    `json:"qty"`
		Sku string `json:"sku"`
	} `json:"lines"`
	Pay struct {
		Charge struct {
			Amount float32 `json:"amount"`
		} `json:"charge"`
		Receipt struct {
			Id string `json:"id"`
		} `json:"receipt"`
	} `json:"pay"`
	Total struct {
		Amount   float32 `json:"amount"`
		Currency string  `json:"currency"`
	} `json:"total"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// PlaceOrderAPIJSONRequestBody defines body for PlaceOrderAPI for application/json ContentType.
type PlaceOrderAPIJSONRequestBody = OrderContextOrder

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /orders)
	PlaceOrderAPI(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PlaceOrderAPI operation middleware
func (siw *ServerInterfaceWrapper) PlaceOrderAPI(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PlaceOrderAPI(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/orders", wrapper.PlaceOrderAPI)
}
